### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#39]
- [ ]  Implement endpoint role
- [ ]  Implement endpoint StatusRequete
- [ ]  Implement endpoint Pays
- [ ]  Implement endpoint Action
- [ ]  Implement endpoint Autorite
- [ ]  Implement endpoint Log
- [ ]  Implement endpoint MotifSuppression
- [ ]  Implement token
- [ ]  Implement Acl
